"""The `Provider` protocol: what the tool table may call.

Every method returns plain JSON-safe data (dicts, lists, strings) so the same
result can be printed by the CLI, returned over MCP, or handed to an agent.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class Provider(Protocol):
    name: str

    # mail
    def mail_search(self, query: str, max_results: int = 10) -> List[Dict[str, Any]]: ...
    def mail_read(self, message_id: str) -> Dict[str, Any]: ...
    def mail_labels(self) -> List[Dict[str, Any]]: ...
    def mail_draft(self, to: List[str], subject: str, body: str,
                   cc: Optional[List[str]] = None) -> Dict[str, Any]: ...
    def mail_send(self, to: List[str], subject: str, body: str,
                  cc: Optional[List[str]] = None) -> Dict[str, Any]: ...

    # drive
    def drive_search(self, text: str = "", q: str = "",
                     max_results: int = 20) -> List[Dict[str, Any]]: ...
    def drive_get(self, file_id: str) -> Dict[str, Any]: ...
    def drive_read(self, file_id: str, max_chars: int = 50000) -> Dict[str, Any]: ...
    def drive_fetch(self, file_id: str) -> Dict[str, Any]: ...
    def drive_upload(self, name: str, content: bytes, mime_type: str = "",
                     parent: str = "") -> Dict[str, Any]: ...

    # calendar
    def calendar_events(self, time_min: str = "", time_max: str = "", calendar: str = "primary",
                        query: str = "", max_results: int = 25) -> List[Dict[str, Any]]: ...
    def calendar_freebusy(self, time_min: str, time_max: str,
                          calendars: List[str]) -> Dict[str, Any]: ...
    def calendar_create(self, summary: str, start: str, end: str, calendar: str = "primary",
                        description: str = "", location: str = "",
                        attendees: Optional[List[str]] = None) -> Dict[str, Any]: ...

    # docs
    def docs_read(self, document_id: str) -> Dict[str, Any]: ...
    def docs_create(self, title: str) -> Dict[str, Any]: ...
    def docs_append(self, document_id: str, text: str) -> Dict[str, Any]: ...

    # sheets
    def sheets_read(self, spreadsheet_id: str, range_: str) -> Dict[str, Any]: ...
    def sheets_append(self, spreadsheet_id: str, range_: str,
                      rows: List[List[str]]) -> Dict[str, Any]: ...

    # directory
    def directory_users(self, query: str = "", max_results: int = 50,
                        domain: str = "") -> List[Dict[str, Any]]: ...
